//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int Id { get; set; }
        public int HastaId { get; set; }
        public Nullable<int> ReceteId { get; set; }
        public Nullable<int> IlacId { get; set; }
        public Nullable<int> UrunAdet { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
    
        public virtual Hasta Hasta { get; set; }
        public virtual Recete Recete { get; set; }
    }
}
