//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDetay
    {
        public int Id { get; set; }
        public int SiparisId { get; set; }
        public Nullable<int> ReceteId { get; set; }
        public int IlacId { get; set; }
        public string SiparisDurumu { get; set; }
        public Nullable<decimal> UrunFiyat { get; set; }
        public Nullable<decimal> UrunKargo { get; set; }
        public Nullable<int> UrunAdet { get; set; }
        public Nullable<decimal> UrunToplam { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
    
        public virtual Siparis Siparis { get; set; }
    }
}
