//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.SiparisDetay = new HashSet<SiparisDetay>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SiparisNo { get; set; }
        public Nullable<int> HastaId { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Email { get; set; }
        public string Gsm { get; set; }
        public string Tc { get; set; }
        public string Adres { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string VergiDairesi { get; set; }
        public string PostaKodu { get; set; }
        public string OdemeTipi { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
    
        public virtual Hasta Hasta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
    }
}
